version: '3.5'

services:

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    image: authentication-service-img
    container_name: ${AUTHENTICATION_SERVICE_NAME}
    restart: always
    ports:
      - "${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}" # Maps the authentication-service port from .env
    environment:
      - AUTHENTICATION_SERVICE_PORT=${AUTHENTICATION_SERVICE_PORT}
      - AUTHENTICATION_SERVICE_NAME=${AUTHENTICATION_SERVICE_NAME}
    env_file:
      - .env
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - mynetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
    driver: local
